fix, implement default constructor for HistRequest
Two reasons do do so:
 1. gcc 4.6 complains according to the C++ standard about
    error: uninitialized const 'dflt' [-fpermissive]
    note: 'const class HistRequest' has no user-provided default constructor
 2. While solving 1. I've noticed that currently both members _useRTH and
    _formatDate could be undefined. That's bad because we use them as default
    when reading from xml.